package ws.client;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.4
 * 2018-09-13T16:44:52.553+08:00
 * Generated source version: 3.1.4
 * 
 */
@WebService(targetNamespace = "http://webserviceimpl.ws/", name = "WebServiceImpl")
@XmlSeeAlso({ObjectFactory.class})
public interface WebServiceImpl {

    @WebMethod
    @Action(input = "http://webserviceimpl.ws/WebServiceImpl/printLogRequest", output = "http://webserviceimpl.ws/WebServiceImpl/printLogResponse")
    @RequestWrapper(localName = "printLog", targetNamespace = "http://webserviceimpl.ws/", className = "com.ws.client.PrintLog")
    @ResponseWrapper(localName = "printLogResponse", targetNamespace = "http://webserviceimpl.ws/", className = "com.ws.client.PrintLogResponse")
    @WebResult(name = "return", targetNamespace = "")
    public String printLog();
}
