
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package ws.client;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.4
 * 2018-09-13T16:44:52.541+08:00
 * Generated source version: 3.1.4
 * 
 */

@WebService(
                      serviceName = "WebServiceImplService",
                      portName = "WebServiceImplPort",
                      targetNamespace = "http://webserviceimpl.ws/",
                      wsdlLocation = "http://127.0.0.1:8123/demo/webservice?wsdl",
                      endpointInterface = "com.ws.client.WebServiceImpl")
                      
public class WebServiceImplPortImpl implements WebServiceImpl {

    private static final Logger LOG = Logger.getLogger(WebServiceImplPortImpl.class.getName());

    /* (non-Javadoc)
     * @see com.ws.client.WebServiceImpl#printLog(*
     */
    public String printLog() {
        LOG.info("Executing operation printLog");
        try {
            String _return = "";
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
