
package ws.client;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.4
 * 2018-09-13T16:44:52.515+08:00
 * Generated source version: 3.1.4
 * 
 */
public final class WebServiceImpl_WebServiceImplPort_Client {

    private static final QName SERVICE_NAME = new QName("http://webserviceimpl.ws/", "WebServiceImplService");

    private WebServiceImpl_WebServiceImplPort_Client() {
    }

    public static void main(String args[]) throws Exception {
        URL wsdlURL = WebServiceImplService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        WebServiceImplService ss = new WebServiceImplService(wsdlURL, SERVICE_NAME);
        WebServiceImpl port = ss.getWebServiceImplPort();  
        
        {
        System.out.println("Invoking printLog...");
        String _printLog__return = port.printLog();
        System.out.println("printLog.result=" + _printLog__return);


        }

        System.exit(0);
    }

}
