package ws.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.4
 * 2018-09-13T16:44:52.564+08:00
 * Generated source version: 3.1.4
 * 
 */
@WebServiceClient(name = "WebServiceImplService", 
                  wsdlLocation = "http://127.0.0.1:8123/demo/webservice?wsdl",
                  targetNamespace = "http://webserviceimpl.ws/") 
public class WebServiceImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://webserviceimpl.ws/", "WebServiceImplService");
    public final static QName WebServiceImplPort = new QName("http://webserviceimpl.ws/", "WebServiceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://127.0.0.1:8123/demo/webservice?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(WebServiceImplService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://127.0.0.1:8123/demo/webservice?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public WebServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public WebServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WebServiceImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public WebServiceImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public WebServiceImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public WebServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns WebServiceImpl
     */
    @WebEndpoint(name = "WebServiceImplPort")
    public WebServiceImpl getWebServiceImplPort() {
        return super.getPort(WebServiceImplPort, WebServiceImpl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WebServiceImpl
     */
    @WebEndpoint(name = "WebServiceImplPort")
    public WebServiceImpl getWebServiceImplPort(WebServiceFeature... features) {
        return super.getPort(WebServiceImplPort, WebServiceImpl.class, features);
    }

}
